spring:
  application:
    name: service-user
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/tienda
    username: postgres
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties.hibernate.format_sql: true

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/
